# Generated by Django 6.0.1 on 2026-01-12 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='timetable_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_sessions', to='attendance.timetable'),
        ),
        migrations.AlterUniqueTogether(
            name='classsession',
            unique_together={('subject', 'scheduled_date', 'start_time')},
        ),
    ]
